version: '3.8'
services:
  postgres-authors:
    image: postgres:12.13
    restart: always
    environment:
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=dspace
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
